version: '2.1'

services:
  datastore_emulator:
    image: singularities/datastore-emulator
    environment:
      DATASTORE_PROJECT_ID: gumo-pullqueue
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"
    command: --no-store-on-disk --consistency=1
