version: '2.1'

services:
  server:
    image: python:3.7.2-stretch
    working_dir: /app
    volumes:
      - .:/app
      - python-cache:/root/.cache/pip
    depends_on:
      - datastore_emulator
    ports:
      - "8080:8080"
    environment:
      DOCKER: "true"
      GOOGLE_CLOUD_PROJECT: gumo-pullqueue
      DATASTORE_EMULATOR_HOST: "datastore_emulator:8081"
    command: make -f tools/Makefile server

  server_test:
    image: python:3.7.2-stretch
    working_dir: /app
    volumes:
      - .:/app
      - python-cache:/root/.cache/pip
    depends_on:
      - datastore_emulator_test
    environment:
      DOCKER: "true"
      PYTEST: "true"
      GOOGLE_CLOUD_PROJECT: gumo-pullqueue
      DATASTORE_EMULATOR_HOST: "datastore_emulator_test:8082"
      USE_TASK_EMULATOR: "true"
    command: make -f tools/Makefile test

  worker:
    image: python:3.7.2-stretch
    working_dir: /app
    volumes:
      - .:/app
      - python-cache:/root/.cache/pip
    depends_on:
      - datastore_emulator
      - server
    environment:
      DOCKER: "true"
      GOOGLE_CLOUD_PROJECT: gumo-pullqueue
    command: make -f tools/Makefile worker

  datastore_emulator:
    image: quay.io/gumo/datastore-emulator:v241
    volumes:
      - datastore-emulator-storage:/opt/data
      - ./sample:/sample
    environment:
      DATASTORE_PROJECT_ID: gumo-pullqueue
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"

  datastore_emulator_test:
    image: quay.io/gumo/datastore-emulator:v241
    environment:
      DATASTORE_PROJECT_ID: gumo-pullqueue
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8082
    ports:
      - "8082:8082"
    command: --no-store-on-disk --consistency=1

volumes:
  python-cache:
    driver: local
  datastore-emulator-storage:
    driver: local
